name:                blog
version:             0.1.0.0
github:              "madf/blog"
license:             BSD-3-Clause
author:              "Maksym Mamontov"
maintainer:          "blog@madf.info"
copyright:           "2025 Maksym Mamontov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/blog#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- scotty >= 0.22
- lucid
- wai
- wai-middleware-static
- wai-extra
- warp
- http-types
- sqlite-simple
- bytestring
- text
- time
- config-ini
- JuicyPixels
- JuicyPixels-extra
- directory
- resource-pool
- mtl
- unliftio-core
- password
- xxhash-ffi
- hashable

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  OverloadedStrings
  LambdaCase

library:
  source-dirs: src

executables:
  blog-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - blog

tests:
  blog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - blog
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
