name:                mbe
version:             0.1.0.0
github:              "madf/blog-engine"
license:             BSD-3-Clause
author:              "Maksym Mamontov"
maintainer:          "blog@madf.info"
copyright:           "2025 Maksym Mamontov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/blog#readme>

dependencies:
- base >= 4.7 && < 5
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages
- -funbox-strict-fields

default-extensions:
  ImportQualifiedPost
  OverloadedStrings
  LambdaCase

library:
  source-dirs: src

  dependencies:
    - aeson
    - bytestring
    - config-ini
    - crypton
    - directory
    - filepath
    - hashable
    - http-types
    - jose < 0.12
    - lens
    - lucid
    - mtl
    - password
    - resource-pool
    - scotty >= 0.22
    - sqlite-simple
    - time
    - unliftio-core
    - wai
    - wai-cors
    - wai-extra
    - wai-middleware-static
    - xxhash-ffi
    - JuicyPixels
    - JuicyPixels-extra

executables:
  mbe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mbe

tests:
  mbe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mbe
    - hspec
    - hspec-wai
    - hspec-wai-json
